# Generated by Django 4.0.2 on 2022-02-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('memberId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('userName', models.CharField(default='NA', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(default='NA', max_length=3)),
                ('zipCode', models.CharField(default='NA', max_length=10)),
                ('image', models.ImageField(upload_to='post_images')),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
    ]
