# Generated by Django 4.0.2 on 2022-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_image_alter_actor_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='image.png', upload_to='', verbose_name='profiles'),
            preserve_default=False,
        ),
    ]
