# Generated by Django 4.0.4 on 2022-07-12 08:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
